# Generated by Django 5.0.2 on 2024-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Слаг категории')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Картинка категории')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг продукта')),
                ('image_large', models.ImageField(upload_to='product_images/large/', verbose_name='Картинка товара в высоком разрешении')),
                ('image_medium', models.ImageField(upload_to='product_images/medium', verbose_name='Картинка товара в среднем разрешении')),
                ('image_low', models.ImageField(upload_to='product_images/low', verbose_name='Картинка товара в низком разрешении')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
