# Generated by Django 5.0.2 on 2024-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество продукта в корзине'),
        ),
    ]
